# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Mario/Downloads/week10_examples/idk_final/idk_final.srcs/sources_1/ip/axi_perf_mon_0/axi_perf_mon_0.xci
# IP: The module: 'axi_perf_mon_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Mario/Downloads/week10_examples/idk_final/idk_final.gen/sources_1/ip/axi_perf_mon_0/axi_perf_mon_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_perf_mon_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Mario/Downloads/week10_examples/idk_final/idk_final.gen/sources_1/ip/axi_perf_mon_0/axi_perf_mon_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_perf_mon_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Mario/Downloads/week10_examples/idk_final/idk_final.gen/sources_1/ip/axi_perf_mon_0/axi_perf_mon_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_perf_mon_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Mario/Downloads/week10_examples/idk_final/idk_final.srcs/sources_1/ip/axi_perf_mon_0/axi_perf_mon_0.xci
# IP: The module: 'axi_perf_mon_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Mario/Downloads/week10_examples/idk_final/idk_final.gen/sources_1/ip/axi_perf_mon_0/axi_perf_mon_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_perf_mon_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Mario/Downloads/week10_examples/idk_final/idk_final.gen/sources_1/ip/axi_perf_mon_0/axi_perf_mon_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_perf_mon_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Mario/Downloads/week10_examples/idk_final/idk_final.gen/sources_1/ip/axi_perf_mon_0/axi_perf_mon_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_perf_mon_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
